const sidebars = {
  HelpSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
    {
      type: 'link',
      label: 'Contact & Support',
      href: '/contact',
    },
  ],
};

export default sidebars;
