const sidebars = {

  HelpSidebar: [
    {
      type: 'category',
      label: 'Shira Help Center',
      link: {
        type: 'doc',
        id: 'welcome',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: '.',
        },
      ],
    },
    {
      type: 'link',
      label: 'Contact & Support',
      href: '/contact',
    },
  ],
};

export default sidebars;
